
function oa_add_ammo()
	local wpn = db.actor:active_item()
	if not IsWeapon(wpn) then 
		return
	end
	
	local ammo_mag_size = ini_sys:r_u32(wpn:section(), "ammo_mag_size")
	local ammo = utils_item.get_ammo(wpn:section(), wpn:id(), true)
	local string_find = string.find
	
	for sec,id in pairs(ammo) do
		if not(string_find(sec,"_verybad") or string_find(sec,"_bad") or string_find(sec,"buck_self")) then
			local ammo_amount = utils_item.get_amount(db.actor, sec)
			if ammo_amount < ammo_mag_size then

				alife_create_item(sec, db.actor, { ammo = ammo_mag_size })
			end
		end		
	end

end

function on_game_start()
	RegisterScriptCallback("actor_on_weapon_reload", oa_add_ammo)
	RegisterScriptCallback("actor_on_weapon_jammed", oa_add_ammo)
	RegisterScriptCallback("actor_on_weapon_no_ammo", oa_add_ammo)
end